/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ru.gorbunov.project.cleaner;

import ru.gorbunov.project.cleaner.plan.DefaultPlanExecutor;

public class Main {

    public static void main(String[] args) {
        if (args == null) {
            return;
        }
        new Cleaner(DefaultPlanExecutor::new).clean(args);
    }
}
